version: '3'
networks:
  default:
    name: pis-development
services:
  # nodejs-server:
  #   build:
  #     context: ./api
  #   ports:
  #     - "3080:3080"
  #   container_name: node-api
  #   volumes:
  #      - ./api:/usr/src/app/api
  #      - /usr/src/app/api/node_modules
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    container_name: pis_app
    stdin_open: true
    volumes:
       - ./app:/app