version: '3'
networks:
  default:
    name: pis-development
services:
  api:
    build:
      context: ./api
    ports:
      - 9080:9080
      - 7777:7777
      - 9443:9443
    container_name: pis-api
    volumes:
       - ./api:/api
  app:
    build:
      context: ./app
    ports:
      - 3000:3000
    container_name: pis-app
    stdin_open: true
    volumes:
       - ./app:/app